### ISSUE TITLE
Create Code and tests for the underlying project

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#13]
Make a project for the final day workshop that supports the learning goals and topics introduced.

**Comment by sofusalbertsen** [comment]
Note to @RandomSort : Did we settle on any coding language?
If yes, then I would use that in the docker exercises.

**Comment by RandomSort** [comment]
We did not.
I think we should use python since it is very ubiquitous :)
Otherwise Go because of coolness.
