### ISSUE TITLE
Prerequisite for the students

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/reveals#17]

**Comment by sofusalbertsen** [comment]
- You can code/script in some language, a little bit.
- You are an student, newly educated or unemployed in the IT sector.

Information:
We will use command line, do not be afraid. If you do not know linux shell, look at this video and article.
This is a 5 days course, day and night, either you are in or you're out.

**Comment by JKrag** [comment]
Also add as prerequiste that students need basic shell knowledge. We provide links to tutorial.

**Comment by JasmineCrozier** [comment]
I would like a decision and a clear message to add on the website by April 6th please.

FYI: Eventbrite offers the option to add a question to all people who wish to register, so we could ask a fun and tech question if you want.

**Comment by sofusalbertsen** [comment]
@JasmineCrozier can I get you to paste in the text detailing the requirements, and closing this issue afterwards?

**Comment by JasmineCrozier** [comment]
As we are getting ready to welcome you on Monday, we'd like to share some information with you.

Mark your calendar: We count on you to attend from 9 to 16.30 and from Monday to Thursday. We are planning lunch each day, a mingle and snacks on Monday evening, and a small celebration on Thursday evening. 
 
Location: We will meet on Monday at 9.00 in Omega room, Jupiter Building, Lindholmen Campus. See this detailed map: http://maps.chalmers.se/#db0dd5e5-c954-41ff-83e0-b0340b91bcbe
 
Wifi: We will use EduRoam, which you can connect to with your student email address. If you do not have access to Eduroam, please contact us.
 
Requirements for the training: 
You should be able to code/script in some language.
We will use command line, do not be afraid. If you do not know linux shell, look at this tutorial, and read from setup to 3. https://swcarpentry.github.io/shell-novice/
 
If you have any questions, please contact us on Facebook or via events@praqma.com
 
Be ready to have smoke coming out of your ears ;)
We look really much forward to having you!
