### ISSUE TITLE
Git Basic section

### ISSUE THREAD

**Issue by JKrag** [Praqma/reveals#2]
- [ ] Add placeholder slides showing the main storyline
- [ ] Add initial slides for actual content
- [ ] Add gitgraph.js graphs (depends on #7 )
- [ ] Flesh out slides
- [ ] Speaker notes
- [ ] Polish design

**Comment by sofusalbertsen** [comment]
Nice slides @RandomSort, just a few questions:
Slide 24: What is it that we do _not_ tell about the truth here? (mention that in the speakers notes so the reasoning behind the slide is clear.
42: Why diff --git, and not git diff?

**Comment by sofusalbertsen** [comment]
After giving the first presentation to the students yesterday, it's clear that we cannot also introduce linux bash in our 4,5 hours, so that will go into the prerequisites.

**Comment by RandomSort** [comment]
I've made an issue the gitkatas repository regarding making a shell kata :)

Also we might just think a bit about why we need the shell.

They can basically use any file explorer for non-git operations and file
manipulation and then only use git bash for git commands.

**Comment by sofusalbertsen** [comment]
For me it seems we can squeeze in the day 1+2 in our 4,5 hours of training at the CodeAcc, if we exclude the shell part.
@JKrag  will go through the slides to see if he misses something so bad that it needs to be there (and points out what then needs to be dropped ;) )

**Comment by JKrag** [comment]
They will still need basic shell knowledge like `cd` and `pwd`. Also `cat` is very useful.

I am not particularly fond of the continuous use of `echo "stuff" > file.txt` approach, but from experience I also know that having people "just use their favourite editor" can be surprisingly slow.

**Comment by RandomSort** [comment]
cat is useful, as is cd, generally though "open git bash here" would solve
their problems.
I would assume this is only relevant for windows / mac users as linux users
can be assume to know basic shell.

Also I've had great success just making a new textfile, open it in notepad
and make changes there. Sometimes people have a hard time figuring out that
Git is not some magically alt world :)
