### ISSUE TITLE
Incorporate Phable template in slideshows

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/reveals#26]
- [ ] Slide with bullets
- [ ] Picture
- [ ] Code
- [ ] Table

**Comment by sofusalbertsen** [comment]
I'm not sure it's phable we need to contact here, cuss it's more CSS and less images (og at least not only images). Will have chat with Mona about it.

**Comment by sofusalbertsen** [comment]
[ACADEMY_SLIDES.pdf](https://github.com/Praqma/reveals/files/719086/ACADEMY_SLIDES.pdf)

**Comment by sofusalbertsen** [comment]
https://trello.com/c/A112iH9G/105-template-for-code-academy-slideshows-design

**Comment by sofusalbertsen** [comment]
[ACADEMY_SLIDES_v2.pdf](https://github.com/Praqma/reveals/files/726144/ACADEMY_SLIDES_v2.pdf)

**Comment by sofusalbertsen** [comment]
http://code.praqma.com/reveals/code-academy/continuous-delivery-story/#/
Only needed to embed both logos in the png and we are ready to go :+1:

**Comment by sofusalbertsen** [comment]
Added on all slide decks in commit: https://github.com/Praqma/reveals/commit/52769149f1f2eedc6a7dd269f0ee5d8a01c59be7

**Comment by sofusalbertsen** [comment]
@JKrag @RandomSort This is what we will get:
Reveals does _not_ support scalable 9X9 pictures, so we are stuck with a fixed image:
But it seems to work on very different resolutions [as tried out here](http://quirktools.com/screenfly/#u=http%3A//code.praqma.com/reveals/code-academy/continuous-delivery-story/%23/&w=800&h=480&a=24)
Close much?

**Comment by JKrag** [comment]
Probably good enough
