### ISSUE TITLE
Follow-up on the workshop materials

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/reveals#27]

**Comment by RandomSort** [comment]
CoDe Academy Plan:
https://docs.google.com/spreadsheets/d/1TvfWotrz8aQu7Ghy397FncpzexIJhflbldAk-O1kDRI/edit#gid=485737939
Graphics and Story:
https://trello.com/c/La3mBNjw/91-code-academy

**Comment by RandomSort** [comment]
Still have some notes I can't obtain due to me forgetting praqma pc today :P

**Comment by RandomSort** [comment]
https://drive.google.com/drive/u/1/folders/0B3mqCwER-jlkWmplbXgtOEVzcEk

**Comment by RandomSort** [comment]
* CD storyline
** Mandag
Mandag morgen skal struktureres.

Starten skal meget tidligere introduceres konceptuelt.

Første modul skal være noget med at motivere CD storylinen i konteksten.

Det minder meget om CD in an embedded world.

Også præsentere hvad vi gerne vil gennemgå hen i gennem ugen.

Der skal være et konkret formål med det der bruges.

Der skal tænkes over indholdet og det skal være mere scripted.

Det giver mening med lego gamet.

*** Lego game
Lego gamet skal raffineres.

Der skal være et læringsmål med hver sprint.
Hvert modul kommer måske til at indeholde to sprints.

** Tirsdag
*** TDD
TDD kunne udgå og blive til Testtyper
eller build og gradle

*** Git 
Kunne måske kortes ned så man fokuserer mere på præcist det Git materiale der enabler fredag

** Onsdag
*** Docker 
Vi vil gerne beholde docker, som mininmum fordi det er sejt at sige at vi underviser dem i Docker
Måske skal der mere tid, måske skal der mindre tid til det.

Fokus på hvad læringsmålet er.

Kigge på hvad vi vil, og få strammet op på materialet.


** Torsdag
Torsdag kunne handle om Jenkins og så blive genbrugt fredag
Jenkins As Code kunne godt dø
Jenkins kunne skæres ned til en halv dag.
Skip JobDSL.
Tilføj måske Workflow. ( Måske kan vi bruge BON til noget her? )
JobDSL vs. Workflow

** Fredag
Kunne være fyldt kun med valgfri opgaver - så de studerende selv kunne vælge hvilken vej de gik
Det fungerede super med dem som lavede deres egne projekter

*** Fremlæggelser
Det var fedt med fremlæggelse måske kunne man være opmærksom på at få
de "dårlige" til at starte, så der ikke er noget præstationsgøgl.


* DevOps Academy?

** Vi har ikke vist noget om langsom vs hurtig feedback
Vi har slet ikke noget om forskellen på forskellige tests, det kunne komme med under TDD i forhold til testing.




* Jenkins as Storyline
Hele ideen er at have den samme storyline som CD, men at have
automatiseringsplatformen som værende perspektivet.

"Lave det som et skoleskema"

Det kan give anledning til at både dem der kan det hele og har svært
ved det hele kan få lidt mere frirum i stedet for lange blokke af 
"kedeligt" materiale.

** Mandag
Stadig en motivational speak om CD, hvorfor er vi er?

Holde fast i LEGO game og task management starten 

Måske er der en pointe i at mandag er uden computere?

Mandag kunne man sige "I må gå hjem, når I har installeret Jenkins manuelt"
Når I ser det her screenshot. Altså uden Jenkins viden.

LEGO gamet kunne også meget vel være længere.

Install Jenkins uden at vide hvad det er giver også mulighed for at
snakke om shell og SSH

"Ingen er færdige før alle er færdige", når alle er færdige spiser vi pizza

** Tirsdag
** Onsdag
** Torsdag
** Fredag
* SW Project as storyline

* Teaching Patterns
** Be honest with the students
** Pain point -> solution
Painkillers?
** Always Recap
** Tell-Demo-Exercise-Walkthrough

* Denne her gang
Frede lunch mandag?

Udlever reference projekt hver dag
Udlever test
