### ISSUE TITLE
Figure out if it would be good from a didactic perspective to use hyper

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#28]
We could possibly use hyper.sh rather than using local Docker instance.

This might blur the learning or enable it?

Hyper might be interested in sponsoring this?

**Comment by JKrag** [comment]
@RandomSort @sofusalbertsen and I discussed this at meeting today.
Summary: We agree that we would actually prefer the Hyper solution.

@JKrag will mail Adam and Mike.

**Comment by sofusalbertsen** [comment]
And hyper has (at least a beta) cli for all three OS, no ops, no cry :)

**Comment by RandomSort** [comment]
if doing docker run hyperhq/hykins you get a jenkins running locally.
Doing the same using hyper cli on windows just results in a stopped container in the hyper cloud.

**Comment by sofusalbertsen** [comment]
Not using Hyper this time around.
