### ISSUE TITLE
Make revised 4-day plan of Code Accademy

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/reveals#29]
The original 5 day plan needs to be shrinked into 4 days.
https://docs.google.com/spreadsheets/d/1TvfWotrz8aQu7Ghy397FncpzexIJhflbldAk-O1kDRI/edit#gid=485737939

**Comment by sofusalbertsen** [comment]
My sugestion is made in the tab named "Agenda 4 days - Sofus edition" feel free to make your own edition, but please provide arguments to your change.

We have to cut down 25% of the course. That is equivalent to one day/ 6 hours of training.

We can either cut things away, set an expectation of the students, or both. What I'm suggesting is the last of the three:
We implement the 90 minute module schedule. That means that our pre lunch schedule is 3,5 hours (30 min recap in the morning). 
This gives us 30 minutes more per day, but this is not the reason we do this!

- Testing is reduced to one module.
- Traceability is removed.
- Git basic is replaced by git advanced git. Prereq is that people have a basic understanding about git (what the pre-req is specifically, we need to agree on).
- In the new version docker gets +30 minutes more than original proposed. I'm not quite sure that is necessary, but it's either that or -1 hour.

So, get ready and make comments :+1:

**Comment by JKrag** [comment]
I had some comments and have now created a new suggestion in a new tab. Sofus has been co-author on this version as well, so his original is now deprecated. We leave it in the spreadsheet for now for "historical" reasons and to give @RandomSort a chance to study both.

**Comment by RandomSort** [comment]
I very much approve of the plan. It seems realistic - and I like the added time to recap each day.
We could still have a post-day recap, but that might be over doing it.
I like that we are removing traceability, because we don't have enough time to add value. And the same thing with regards to removing TDD and instead talking of testtypes and similar things.

**Comment by sofusalbertsen** [comment]
Closing this, as agreed upon :+1:
