### ISSUE TITLE
Hyper build?

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/reveals#31]
Talk to Mark Coleman about support for hyper build

**Comment by JKrag** [comment]
I have argued for this feature on Hypers roadmap trello board: https://trello.com/c/T2a0tSRg

I also talked very briefly with mark about this when I met him in Brussels Saturday.

**Comment by JKrag** [comment]
Support for Hyper build is still an open question, but we can't do much more for now. I will keep an eye on the Hyper roadmap issue, and follow up as needed.
As the decision on using Hyper is not final anyway, we are closing this issue for now.
