### ISSUE TITLE
Jenkins Basic - Slides

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#4]
- [ ] Add placeholder slides showing the main storyline
- [ ] Add initial slides for actual content
- [ ] Flesh out slides
- [ ] Polish design

**Comment by sofusalbertsen** [comment]
The slides start from could either be:
http://code.praqma.com/reveals/jenkins-intro/#/
Or find the material that was used last year.

**Comment by sofusalbertsen** [comment]
http://code.praqma.com/reveals/code-academy/basic-jenkins/#/
