### ISSUE TITLE
Jenkins Continued - Slides

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#5]
- [ ] Add placeholder slides showing the main storyline
- [ ] Add initial slides for actual content
- [ ] Flesh out slides
- [ ] Polish design

**Comment by sofusalbertsen** [comment]
Agenda:
You know Jenkins
No more pointy pointy, cliky cliky
Introducing Pipelines
Vocabulary:
Making your first pipeline hello world + checkout of sourcecode.
Stages and pack/unpack
Parallel and archiving

**Comment by meekrosoft** [comment]
Any links to this?  I need to learn pipelines myself :)

**Comment by sofusalbertsen** [comment]
Sorry @meekrosoft 
https://github.com/Praqma/reveals/tree/gh-pages/code-academy/advanced-jenkins
They are not Done Done, but it's a good start :)

**Comment by sofusalbertsen** [comment]
And exercises here: https://github.com/praqma-training/gildedrose
