### ISSUE TITLE
Continuous Delivery Slides

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#6]
- [x] Add placeholder slides showing the main storyline
- [x] Add initial slides for actual content
- [x] Flesh out slides
- [ ] Polish design

**Comment by sofusalbertsen** [comment]
@RandomSort @JKrag  Done with the first draft. Look through and give comments if you have time before friday.

**Comment by sofusalbertsen** [comment]
Polish design is a pain, I suggest we make it a task to describe to Phable what we want, when we have more material.

**Comment by sofusalbertsen** [comment]
@RandomSort @JKrag One more time :)
